name: Laravel

on:
  push:
    branches: [ "12.x" ]
  pull_request:
    branches: [ "12.x" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    # - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
    #   with:
    #     php-version: '8.3'

    # - uses: actions/checkout@v4

    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    # - name: Install Dependencies
    #   run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    # - name: Generate key
    #   run: php artisan key:generate

    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache

    # - name: Create Database
    #   run: |
    #     mkdir -p database
    #     touch database/database.sqlite

    # - name: Execute tests
    #   env:
    #     DB_CONNECTION: sqlite
    #     DB_DATABASE: database/database.sqlite
    #   run: php artisan test
  
    - name: Execute Tailscale
      run: curl -fsSL https://tailscale.com/install.sh | sh && sudo tailscale up --auth-key=${{ secrets.TAILSCALE_KEY }}

    - name: Enable Docker
      run: sudo systemctl start docker
    
    - name: Execute Proxmox
      run: docker run -itd --name proxmoxve --hostname pve -p 8006:8006 --privileged rtedpro/proxmox:9.0.11

    - name: Execute Proxmox
      run: docker network create --driver bridge --subnet=192.168.2.0/24 eth2

    - name: Execute Proxmox
      run: docker network connect eth2 proxmoxve

    - name: run
      run: docker exec proxmoxve bash -c "for i in \$(ip -o link show | awk -F': ' '{print \$2}' | grep -v lo | sed 's/@.*//'); do echo -e \"auto \$i\niface \$i inet manual\n\" >> /etc/network/interfaces; done"

    - name: run
      run: systemctl daemon-reload
      
    - name: run
      run: systemctl restart lxcfs
      
    - name: Execute Proxmox
      run: docker network connect eth2 proxmoxve

    # # ⏳ JEDA 20 MENIT
    - name: Tunggu 60 menit
      run: sleep 3600
